// Post-build step: produce per-route HTML files in dist/ with route-specific
// title / description / canonical / og / twitter / JSON-LD baked in.
//
// Why: Hielda is an SPA, so on first crawl Google sees the same index.html
// for every route. The per-route document.title updates in App.jsx happen
// client-side after JS runs, which Google's crawler treats unreliably. With
// these per-route HTML files served via vercel.json rewrites, each marketing
// page (calculator, letter template, how, privacy) ships unique meta in the
// HTML response itself.

import fs from "node:fs"
import path from "node:path"
import { createServer } from "vite"

const DIST = "dist"
const SITE = "https://hielda.com"

// Route table shared with App.jsx so the head a crawler gets at first
// fetch and the head the client sets after mounting are the same thing.
const { SEO_ROUTES } = await import("../src/data/seoRoutes.js")
const routes = SEO_ROUTES.filter((r) => r.file).map((r) => ({ ...r, canonical: r.path === "/" ? `${SITE}/` : `${SITE}${r.path}` }))

function escapeAttr(s) {
  return String(s).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}
function escapeText(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

function setMetaContent(html, selector, value) {
  const re = new RegExp(`(<meta\\s+${selector}\\s+content=")[^"]*(")`, "i")
  if (!re.test(html)) return html
  return html.replace(re, `$1${escapeAttr(value)}$2`)
}

function setTitle(html, title) {
  return html.replace(/<title>[^<]*<\/title>/i, `<title>${escapeText(title)}</title>`)
}

function setCanonical(html, url) {
  return html.replace(/(<link\s+rel="canonical"\s+href=")[^"]*(")/i, `$1${escapeAttr(url)}$2`)
}

function injectSchemas(html, schemas) {
  if (!schemas?.length) return html
  const blocks = schemas
    .map(s => `    <script type="application/ld+json">${JSON.stringify(s)}</script>`)
    .join("\n")
  return html.replace("</head>", `${blocks}\n  </head>`)
}

const baseHtmlPath = path.join(DIST, "index.html")
if (!fs.existsSync(baseHtmlPath)) {
  console.error(`prerender: ${baseHtmlPath} not found — has \`vite build\` run?`)
  process.exit(1)
}
const baseHtml = fs.readFileSync(baseHtmlPath, "utf-8")

// Render each marketing page's body to static HTML so a crawler sees the
// article rather than an empty <div id="root">. Only the <head> was being
// prerendered before, and Search Console had indexed 6 of the 15 pages.
// Vite's SSR loader resolves JSX / CSS modules / import.meta.env exactly as
// the client build does, so class names match the emitted stylesheet.
const vite = await createServer({
  configFile: "vite.config.js",
  server: { middlewareMode: true, hmr: false },
  appType: "custom",
  logLevel: "error",
})
const { render } = await vite.ssrLoadModule("/scripts/ssr-entry.jsx")

function setBody(html, markup) {
  if (!markup) return html
  if (!html.includes('<div id="root"></div>')) {
    throw new Error('prerender: <div id="root"></div> not found in index.html')
  }
  return html.replace('<div id="root"></div>', `<div id="root">${markup}</div>`)
}

let written = 0
for (const route of routes) {
  let html = baseHtml
  html = setBody(html, render(route.file))
  html = setTitle(html, route.title)
  html = setMetaContent(html, 'name="description"', route.description)
  html = setCanonical(html, route.canonical)
  html = setMetaContent(html, 'property="og:title"', route.title)
  html = setMetaContent(html, 'property="og:description"', route.description)
  html = setMetaContent(html, 'property="og:url"', route.canonical)
  html = setMetaContent(html, 'name="twitter:title"', route.title)
  html = setMetaContent(html, 'name="twitter:description"', route.description)
  if (route.ogImage) {
    // Per-page share card (generated by build-og-image.mjs). The alt
    // doubles as the page title for screen-reader link previews.
    html = setMetaContent(html, 'property="og:image"', route.ogImage)
    html = setMetaContent(html, 'property="og:image:alt"', route.title)
    html = setMetaContent(html, 'name="twitter:image"', route.ogImage)
  }
  html = injectSchemas(html, route.extraSchemas)

  fs.writeFileSync(path.join(DIST, route.file), html)
  written++
  console.log(`prerender: wrote ${route.file}`)
}
await vite.close()
console.log(`prerender: ${written} files written to ${DIST}/`)
